apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: melita
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - melita.lb.djnd.si
      secretName: melita-tls
  rules:
    - host: melita.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: melita
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: melita-nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://melita.lb.djnd.si"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - files.melita.lb.djnd.si
      secretName: melita-nginx-tls
  rules:
    - host: files.melita.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: melita-nginx
                port:
                  number: 80
