apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: melita
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
images:
  - name: melita
    newName: rg.fr-par.scw.cloud/djnd/melita
    newTag: 'f0bdb0293e03b7729c89d8ad93446b6c4ee12e4b'
