apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: melita
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: melita
    newName: rg.fr-par.scw.cloud/djnd/melita
    newTag: '226e3faa5165077ff45f3459dfc43119dbe90917'
