apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: melita
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
images:
  - name: melita
    newName: rg.fr-par.scw.cloud/djnd/melita
    newTag: '9fc43256c478d179baac19a4c42406ef86b84a88'
