apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: melita
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: melita
    newName: rg.fr-par.scw.cloud/djnd/melita
    newTag: 'c93a7dbb3b01f714bf95a29a92755839813ea9c9'
