version: '3'

volumes:
  postgres-data:


services:
  wagtail:
    build: ./melita
    working_dir: /app
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - ./melita:/app:delegated,rw
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: melita.settings.k8s
      DJANGO_DEBUG: "true"
      DJANGO_DATABASE_HOST: db
      DJANGO_DATABASE_NAME: wagtail
      DJANGO_DATABASE_USER: wagtail
      DJANGO_DATABASE_PASSWORD: changeme
    depends_on:
      - db

  db:
    image: postgres:12.3-alpine
    environment:
      POSTGRES_DB: wagtail
      POSTGRES_USER: wagtail
      POSTGRES_PASSWORD: changeme
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
