# Generated by Django 4.1.4 on 2023-02-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_genericpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="aim",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="activity",
            name="description",
            field=models.TextField(),
        ),
    ]
