# Generated by Django 4.1.7 on 2023-05-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_activity_aim_alter_activity_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="prep_time",
            field=models.IntegerField(choices=[(1, "*"), (2, "**"), (3, "***")]),
        ),
    ]
