# Generated by Django 4.1.7 on 2023-06-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_alter_instructionmethod_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="duration",
            name="name_et",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="duration",
            name="name_nl",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="duration",
            name="name_pl",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="duration",
            name="name_sl",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="duration",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
