# Generated by Django 4.1.7 on 2023-07-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_duration_name_et_duration_name_nl_duration_name_pl_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="aim",
            field=models.TextField(blank=True, null=True),
        ),
    ]
